pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('Access-key')
        AWS_SECRET_ACCESS_KEY = credentials('secret')
        AWS_DEFAULT_REGION = "us-east-1"
    }
    stages {
        stage('Checkout SCM'){
            steps{
                script{
                    checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Prashanthreddybs/my-test']])
                }
            }
        }
        stage('Initializing Terraform'){
            steps{
                script{
                    dir('assessment-deployment/EKS'){
                        sh 'terraform init'
                    }
                }
            }
        }
        stage('Formatting Terraform Code'){
            steps{
                script{
                    dir('assessment-deployment/EKS'){
                        sh 'terraform fmt'
                    }
                }
            }
        }
        stage('Validating Terraform'){
            steps{
                script{
                    dir('assessment-deployment/EKS'){
                        sh 'terraform validate'
                    }
                }
            }
        }
        stage('Previewing the Infra using Terraform'){
            steps{
                script{
                    dir('assessment-deployment/EKS'){
                        sh 'terraform plan'
                    }
                }
            }
        }
        
      stage('Creating/Destroying an EKS Cluster'){
            steps{
                script{
                    dir('assessment-deployment/EKS') {
                        sh 'terraform apply --auto-approve'
                    }
                }
            }
        }
        stage('Deploying PHP  Application') {
            steps{
                script{
                    dir('assessment-deployment/EKS/ConfigurationFiles') {
                        sh 'aws eks update-kubeconfig --region ap-south-1 --name test1'
                        sh 'kubectl apply -f deployment.yaml'
                        sh 'kubectl apply -f service.yaml'
                        sh 'kubectl apply -f autoscale.yaml'
                    }
                }
            }
        }  
    }
}
