apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: my-app1
  labels:
    app: php
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: php
  type: NodePort
